### ISSUE TITLE
Buy transactions error

### ISSUE THREAD

**Issue by ngtianxun08** [fdundjer/solana-sniper-bot#38]
Encountering this error sometime, not always.

```
[08:30:02.429] ERROR: Failed to process pool
    status: "8481abfe57889b06"
    nonce: "35c01846637f68fb"
    maxOrder: "553beb1adc39c4da"
    depth: "0100000000f0a098"
    baseDecimal: "b244fbdde3fb7667"
    quoteDecimal: "ed2ffaab54205e65"
    state: "3846d74dd270550f"
    resetFlag: "1f51148ef48039aa"
    minSize: "06b73f891e"
    volMaxCutRatio: "00"
    amountWaveRatio: "00"
    baseLotSize: "00"
    quoteLotSize: "00"
    minPriceMultiplier: "010100000000"
    maxPriceMultiplier: "1f1df000"
    systemDecimalValue: "00"
    minSeparateNumerator: "00"
    minSeparateDenominator: "00"
    tradeFeeNumerator: "00"
    tradeFeeDenominator: "00"
    pnlNumerator: "00"
    pnlDenominator: "00"
    swapFeeNumerator: "00"
    swapFeeDenominator: "00"
    baseNeedTakePnl: "00"
    quoteNeedTakePnl: "00"
    quoteTotalPnl: "00"
    baseTotalPnl: "00"
    poolOpenTime: "00"
    punishPcAmount: "00"
    punishCoinAmount: "00"
    orderbookToInitTime: "00"
    swapBaseInAmount: "00"
    swapQuoteOutAmount: "00"
    swapBase2QuoteFee: "00"
    swapQuoteInAmount: "00"
    swapBaseOutAmount: "00"
    swapQuote2BaseFee: "00"
    baseVault: "11111111111111111111111111111111"
    quoteVault: "11111111111111111111111111111111"
    baseMint: "11111111111111111111111111111111"
    quoteMint: "11111111111111111111111111111111"
    lpMint: "11111111111111111111111111111111"
    openOrders: "11111111111111111111111111111111"
    marketId: "11111111111111111111111111111111"
    marketProgramId: "11111111111111111111111111111111"
    targetOrders: "11111111111111111111111111111111"
    withdrawQueue: "11111111111111111111111111111111"
    lpVault: "11111111111111111111111111111111"
    owner: "11111111111111111111111111111111"
    lpReserve: "00"
    padding: [
      "00",
      "00",
      "00"
    ]
    error: {
      "type": "Error",
      "message": "Number can only safely store up to 53 bits",
      "stack":
          Error: Number can only safely store up to 53 bits
              at assert (/root/solana-sniper-bot/node_modules/bn.js/lib/bn.js:6:21)
              at BN.toNumber (/root/solana-sniper-bot/node_modules/bn.js/lib/bn.js:547:7)
              at createPoolKeys (/root/solana-sniper-bot/liquidity/liquidity.ts:98:43)
              at /root/solana-sniper-bot/buy.ts:430:41
              at Generator.next (<anonymous>)
              at fulfilled (/root/solana-sniper-bot/buy.ts:28:58)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
    }

```

**Comment by ngtianxun08** [comment]
Changed liquidity/liquidity.ts to

```
baseDecimals: Number.parseInt(accountData.baseDecimal.toString()),
quoteDecimals: Number.parseInt(accountData.quoteDecimal.toString()),
```
