### ISSUE TITLE
Non base58 character exception

### ISSUE THREAD

**Issue by fabiolous** [fdundjer/solana-sniper-bot#53]
This is what happens if i start the script:

PS D:\dev\solana-sniper-bot> npm run buy

> buy
> ts-node buy.ts

bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
D:\dev\solana-sniper-bot\node_modules\base-x\src\index.js:113
    throw new Error('Non-base' + BASE + ' character')
          ^
Error: Non-base58 character
    at Object.decode (D:\dev\solana-sniper-bot\node_modules\base-x\src\index.js:113:11)
    at D:\dev\solana-sniper-bot\buy.ts:103:39
    at Generator.next (<anonymous>)
    at D:\dev\solana-sniper-bot\buy.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (D:\dev\solana-sniper-bot\buy.ts:27:12)
    at init (D:\dev\solana-sniper-bot\buy.ts:96:12)
    at D:\dev\solana-sniper-bot\buy.ts:376:9
    at Generator.next (<anonymous>)
    at D:\dev\solana-sniper-bot\buy.ts:31:71
PS D:\dev\solana-sniper-bot>

**Comment by fdundjer** [comment]
@fabiolous Most likely you are adding a wallet private key as array instead of encoded base58 string.
To fix this, you can use Phantom wallet to export private key.
